config/routes.rb
Rails.application.routes.draw do

  get 'atm/index', as: :atm
  post 'atm/authenticate', as: :atm_authenticate
  post 'atm/finish', as: :finish
  post 'atm/withdraw', as: :withdraw

  # the following line is only for testing purposes
  post 'atm/refill', as: :refill

  get 'welcome/index', as: :welcome
  root "welcome#index"

end

app/models/atm_machine.rb
class AtmMachine

  class << self
    attr_accessor :current_account

    def finish_transactions
      @current_account = nil
    end

    def authenticate(card_number, pin)
      card = Card.where(number: card_number, pin: pin).includes(bank_account: [:user]).first
      raise_invalid_credentials unless card
      raise_expired_card if card.expired?
      @current_account = card.bank_account
    end

    def withdraw(amount=0)
      raise_not_a_number unless amount.is_a? Integer
      raise_user_not_logged_in unless @current_account
      @current_account.dispense(amount)
    end

    def current_account_balance
      raise_user_not_logged_in unless current_account
      current_account.balance
    end

    def current_account_funds
      raise_user_not_logged_in unless current_account
      current_account.current_funds
    end

    private
    def raise_invalid_credentials
      raise InvalidAccessError, "Invalid Credentials."
    end

    def raise_expired_card
      raise InvalidAccessError, "Your card has expired."
    end

    def raise_user_not_logged_in
      raise InvalidAccessError, "There isn't a valid user logged in."
    end

    def raise_not_a_number
      raise NotANumberError, "not a number"
    end

    def account_has_no_funds?
      !current_account.has_funds?
    end
  end

end

class InvalidAccessError < StandardError; end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base

  belongs_to :user, dependent: :destroy
  belongs_to :currency
  has_one :card

  validates :number, numericality: { only_integer: true}, length: { is: 6 }
  validates :number, uniqueness: true

  def in_dollars?
    currency.dollars?
  end

  def in_colones?
    currency.colones?
  end

  def has_funds?
    balance > 0
  end

  def has_enough?(amount)
    new_balance(amount) >= 0
  end

  def dispense(amount)
    raise NotANumberError, "Not a number" unless amount.is_a? Integer
    raise NotEnoughFunds, "Not enough funds" unless has_enough?(amount)
    save_new_balance(amount)
    prepend_currency(amount)
  end

  def current_funds
    prepend_currency(balance)
  end

  private
  def save_new_balance(amount)
    self.balance = new_balance(amount)
    save
  end

  def new_balance(amount)
    balance - amount
  end

  def prepend_currency(amount)
    "#{currency.symbol}#{amount}"
  end
end

class NotEnoughFunds < StandardError; end
class NotANumberError < StandardError; end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :bank_account, dependent: :destroy

  scope :credit, ->{ where(type: :credit) }
  scope :debit, ->{ where(type: :debit) }

  delegate :user, to: :bank_account

  validates :number, numericality: { only_integer: true }, length: { is: 4 }
  validates :number, uniqueness: true
  validates :pin, numericality: { only_integer: true }, length: { is: 4 }

  def expired?
    Date.today > expiration_date
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base

  def dollars?
    currency == "dollars"
  end

  def colones?
    currency == "colones"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bank_accounts
  has_many :cards, through: :bank_accounts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def change_current_account_if_necessary
    session[:current_account] = AtmMachine.current_account.try(:id)
  end

  def current_account
    session[:current_account]
  end

  def current_account=(account)
    session[:current_account] = account
  end

end

app/controllers/atm_controller.rb
class AtmController < ApplicationController

  before_filter :change_current_account_if_necessary, except: [ :authenticate ]
  before_filter :verify_current_account, except: [ :authenticate ]

  def index
  end

  def authenticate
    begin
      if authenticate_user
        redirect_to action: "index"
      end
    rescue InvalidAccessError => e
      flash[:error] = e.message
      redirect_to_login
    end
  end

  def withdraw
    respond_to do |format|
      begin
        amount = AtmMachine.withdraw(params[:amount].to_i)
        format.json{ render json: { success: true, new_balance: AtmMachine.current_account_funds, dispensed: amount, new_amount: AtmMachine.current_account_balance } }
      rescue StandardError => e
        format.json{ render json: { error: true, message: e.message } }
      end
    end
  end

  def finish
    nullify_current_account
    redirect_to_login
  end

  # this is only for testing purposes. didn't even bother to write a test for this
  def refill
    AtmMachine.current_account.update balance: AtmMachine.current_account_balance + 1000
    respond_to do |format|
      format.json{ render json: {success: true, new_balance: AtmMachine.current_account_funds } }
    end
  end

  private
  def redirect_to_login
    redirect_to welcome_url
  end

  def authenticate_user
    AtmMachine.authenticate(params[:number], params[:pin])
    session[:current_account] = AtmMachine.current_account.id
  end

  def verify_current_account
    redirect_to_login and return unless current_account
    @current_account = BankAccount.find current_account
  end

  def nullify_current_account
    AtmMachine.current_account = nil
    session[:current_account] = nil
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :change_current_account_if_necessary, :redirect_to_atm_if_logged

  def index
  end

  private
  def redirect_to_atm_if_logged
    redirect_to atm_url if current_account
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atm_helper.rb
module AtmHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/atm/index.html.erb
<div id='content'>


  <h1>Account No. <%= @current_account.number %></h1>

  <p>Current funds: <span id='current_funds'><%= @current_account.current_funds %></span></p>
  <div id='withdraw'>
    <p>Please type in the amount to withdraw</p>
    <%= form_tag(withdraw_url, remote: true, 'data-type' => 'json') do %>
      <%= text_field_tag :amount, "", size: 10 %>
      <%= submit_tag 'Withdraw' %>
      <%= image_tag 'ajax-loader.gif', class: 'ajax-loader' %>
    <% end %>

    <div class='form'>
      <%= form_tag(finish_url) do %>
        <%= submit_tag 'Finish' %>
      <% end %>
    </div>
  </div>

  <div id='refill_info'>
    <h4>Hint</h4>
    <p>
      <%= link_to "Refill +1000", refill_url, remote: true, id: 'refill', method: :post %>
      (testing purposes)
    </p>
  </div>

  <div class='clear'></div>

  <div class='alert' id='withdraw_error'>
  </div>

  <div class='alert' id='withdraw_success'>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='main-content'>

  <% if flash[:error] %>
    <div id='error_message'>
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome to ATM</h2>

<p>Please type in your credit/debit card number and pin.</p>

<div class='table'>
<%= form_tag(atm_authenticate_path) do %>
  <div class='row'>
    <div class='cell'>
      <%= label_tag :number %>
    </div>
    <div class='cell'>
      <%= text_field_tag :number %>
    </div>
  </div>
  <div class='row'>
    <div class='cell'>
      <%= label_tag :pin, "PIN" %> 
    </div>
    <div class='cell'>
      <%= password_field_tag :pin %>
    </div>
  </div>
  <div class='row'>
    <div class='cell'>
      <%= submit_tag "Log In" %>
    </div>
  </div>
  <div>
    <h3>Hint - Use any of the following credit cards</h3>
    <p>Number: 1234 / PIN: 1234</p>
    <p>Number: 5678 / PIN: 5678</p>
  </div>
<% end %>
</div>